// tslint:disable
/**
 * Mock API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    ApiEffectResult,
} from '../models';

export interface AppControllerGetIconsRequest {
    group: AppControllerGetIconsGroupEnum;
}

export interface AppControllerPostIconRequest {
    group: AppControllerPostIconGroupEnum;
    requestBody: Array<string>;
}

/**
 * no description
 */
export class AppApi extends BaseAPI {

    /**
     */
    appControllerGetIcons({ group }: AppControllerGetIconsRequest): Observable<ApiEffectResult>
    appControllerGetIcons({ group }: AppControllerGetIconsRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiEffectResult>>
    appControllerGetIcons({ group }: AppControllerGetIconsRequest, opts?: OperationOpts): Observable<ApiEffectResult | AjaxResponse<ApiEffectResult>> {
        throwIfNullOrUndefined(group, 'group', 'appControllerGetIcons');

        return this.request<ApiEffectResult>({
            url: '/icons/{group}'.replace('{group}', encodeURI(group)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    appControllerPostIcon({ group, requestBody }: AppControllerPostIconRequest): Observable<ApiEffectResult>
    appControllerPostIcon({ group, requestBody }: AppControllerPostIconRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiEffectResult>>
    appControllerPostIcon({ group, requestBody }: AppControllerPostIconRequest, opts?: OperationOpts): Observable<ApiEffectResult | AjaxResponse<ApiEffectResult>> {
        throwIfNullOrUndefined(group, 'group', 'appControllerPostIcon');
        throwIfNullOrUndefined(requestBody, 'requestBody', 'appControllerPostIcon');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ApiEffectResult>({
            url: '/icons/{group}'.replace('{group}', encodeURI(group)),
            method: 'POST',
            headers,
            body: requestBody,
        }, opts?.responseOpts);
    };

}

/**
 * @export
 * @enum {string}
 */
export enum AppControllerGetIconsGroupEnum {
    Insects = 'insects'
}
/**
 * @export
 * @enum {string}
 */
export enum AppControllerPostIconGroupEnum {
    Insects = 'insects'
}
