name: 📖 deploy + 📦 release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js 26
        uses: actions/setup-node@v6
        with:
          node-version: 26
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Create release PR or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release-ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./packages/demo/dist"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
